# Generated by Django 2.2 on 2019-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190420_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
